export const SEARCH_MOVIE="SEARCH_MOVIE"
export const FETCH_MOVIES='FETCH_MOVIES'
export const FETCH_MOVIE='FETCH_MOVIE'
export const FETCH_MOVIES_ERROR='FETCH_MOVIES_ERROR'
export const START_LOADING='START_LOADING'
export const STOP_LOADING='STOP_LOADING'